/*
 *  Copyright (C) 2010 Apertum project. web: www.apertum.ru email: info@apertum.ru
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package ru.apertum.qsystem.client.forms;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JFrame;
import org.dom4j.Element;
import org.jdesktop.application.Application;
import org.jdesktop.application.ResourceMap;
import ru.apertum.qsystem.common.Uses;
import ru.apertum.qsystem.common.model.NetCommander;
import ru.apertum.qsystem.common.model.INetProperty;
import ru.apertum.qsystem.QSystem;

/**
 * Диалог получения названия услуги для переадресации и сопутствующих параметров.
 * Created on 29 Сентябрь 2008 г., 10:30
 * Класс диалоговой формы с выбором требуемой услуги из выпадающего списка.
 * Также сдесь можно разместить сопутствующие элементы ввода др. параметров.
 * @author Evgeniy Egorov
 */
public class FRedirect extends JDialog {

    /**
     * Результат
     */
    private static boolean ok;
    /**
     * Используемая ссылка на диалоговое окно.
     */
    private static FRedirect servicesForm;

    private static ResourceMap localeMap = null;

    private static String getLocaleMessage(String key) {
        if (localeMap == null) {
            localeMap = Application.getInstance(QSystem.class).getContext().getResourceMap(FRedirect.class);
        }
        return localeMap.getString(key);
    }

    /** Creates new form FRedirect
     * @param netProperty
     * @param owner 
     */
    public FRedirect(INetProperty netProperty, JFrame owner) {
        super(owner, getLocaleMessage("redirect.caption"), true);
        initComponents();

        buttonOk.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                ok = true;
                setVisible(false);
            }
        });
        buttonCancel.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                ok = false;
                setVisible(false);
            }
        });

        final Element services = NetCommander.getServiсes(netProperty);
        if (services == null) {
            throw new Uses.ClientException("Невозможно получить список предлагаемых услуг.");
        }
        final List<Element> elUsers = Uses.elements(services, Uses.TAG_SERVICE);

        for (int i = 0; i < elUsers.size(); i++) {
            final String s = elUsers.get(i).attributeValue(Uses.TAG_NAME);
            comboBoxServices.addItem(s);
        }
        comboBoxServices.setSelectedIndex(0);

        setLocation(Math.round(owner.getLocation().x + owner.getWidth() / 2 - getWidth() / 2),
                Math.round(owner.getLocation().y + owner.getHeight() / 2 - getHeight() / 2));
    }

    /**
     * Выбор услуги для перенаправления.
     * @param netProperty свойства коннекта
     * @param owner относительно этого контрола модальность и позиционирование
     * @return класс полусения свойств
     */
    public static FRedirect getService(INetProperty netProperty, JFrame owner) {
        Uses.log.logger.info("Выбор услуги для перенаправления.");
        if (servicesForm == null) {
            servicesForm = new FRedirect(netProperty, owner);
        }
        servicesForm.setLocation(Math.round(owner.getLocation().x + owner.getWidth() / 2 - servicesForm.getWidth() / 2),
                Math.round(owner.getLocation().y + owner.getHeight() / 2 - servicesForm.getHeight() / 2));
        servicesForm.setVisible(true);
        return ok ? servicesForm : null;
    }

    public String getServiceName() {
        return (String) servicesForm.comboBoxServices.getSelectedItem();
    }

    public boolean getRequestBack() {
        return servicesForm.checkBoxBack.isSelected();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonOk = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        checkBoxBack = new javax.swing.JCheckBox();
        comboBoxServices = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        ResourceMap resourceMap = Application.getInstance(QSystem.class).getContext().getResourceMap(FRedirect.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);

        buttonOk.setText(resourceMap.getString("buttonOk.text")); // NOI18N
        buttonOk.setName("buttonOk"); // NOI18N

        buttonCancel.setText(resourceMap.getString("buttonCancel.text")); // NOI18N
        buttonCancel.setName("buttonCancel"); // NOI18N

        checkBoxBack.setText(resourceMap.getString("checkBoxBack.text")); // NOI18N
        checkBoxBack.setName("checkBoxBack"); // NOI18N

        comboBoxServices.setName("comboBoxServices"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setIcon(resourceMap.getIcon("jLabel2.icon")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonOk)
                        .addGap(18, 18, 18)
                        .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addComponent(checkBoxBack)
                    .addComponent(comboBoxServices, 0, 262, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxServices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkBoxBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonOk)
                            .addComponent(buttonCancel)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonOk;
    private javax.swing.JCheckBox checkBoxBack;
    private javax.swing.JComboBox comboBoxServices;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
